### ISSUE TITLE
Make Dashtag into a rails engine

### ISSUE THREAD

**Issue by anirudh-eka** [anirudh-eka/dashtag#73]

**Comment by pturley** [comment]
I am open to helping with this one.  I was thinking that we might make this repo be just the gem with the rails engine.  Then we could make another repo called something like "dashtag-solo" which would be just a rails app that mounts the engine.  That way we would have both an example implementation as well as a repo people could fork and deploy to heroku to do standalone dashtaggy goodness.  What do you guys think?
