### ISSUE TITLE
break TWITTER_BEARER_CREDENTIALS into two env variables

### ISSUE THREAD

**Issue by anirudh-eka** [anirudh-eka/dashtag#94]
right now 
`TWITTER_BEARER_CREDENTIALS=your_twitter_key:your_twitter_secret`
Let's make it so the user doesn't have to put the key and secret together

**Comment by anirudh-eka** [comment]
We will need to update dashtag solo to take the 2 new env variables

**Comment by nchambe2** [comment]
I pushed the refactoring change that we were working on. The test are passing. I think we can close this card.

**Comment by anirudh-eka** [comment]
Great! I just updated Dashtag_Solo and tested it. One small thing: 

I noticed that twitter is calling the key "Consumer Key" and the secret 'Consumer Secret'; so let's keep our env variable names as close as possible to it. So let's change:

`TWITTER_BEARER_KEY` to `TWITTER_CONSUMER_KEY`
and
`TWITTER_BEARER_SECRET` to `TWITTER_CONSUMER_SECRET`
